<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>slim</string>
	</array>
	<key>name</key>
	<string>Slim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#slim-comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruby-logic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruby-content</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ruby-embedded</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-unenclosed</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-enclosed-1</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-enclosed-2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-enclosed-3</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ruby-content</key>
		<dict>
			<key>begin</key>
			<string>==?'? </string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>source.ruby.embedded</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>ruby-embedded</key>
		<dict>
			<key>begin</key>
			<string>#{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>source.ruby.embedded</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>ruby-logic</key>
		<dict>
			<key>begin</key>
			<string>^\s*-</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>source.ruby.embedded</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>slim-comment</key>
		<dict>
			<key>match</key>
			<string>\s*/.*$</string>
			<key>name</key>
			<string>comment.line.slash.slim</string>
		</dict>
		<key>tag-enclosed-1</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s*|:\s*)([A-Za-z.#][A-Za-z0-9_.#-]*+)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>text.slim.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
			</array>
		</dict>
		<key>tag-enclosed-2</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s*|:\s*)([A-Za-z.#][A-Za-z0-9_.#-]*+)\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>text.slim.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
			</array>
		</dict>
		<key>tag-enclosed-3</key>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Za-z.#][A-Za-z0-9_.#-]*+)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>text.slim.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
			</array>
		</dict>
		<key>tag-param-name</key>
		<dict>
			<key>match</key>
			<string>[A-Za-z-]+(?==)</string>
			<key>name</key>
			<string>entity.name.param.slim</string>
		</dict>
		<key>tag-param-value-enclosed-1</key>
		<dict>
			<key>begin</key>
			<string>=\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>tag-param-value-enclosed-2</key>
		<dict>
			<key>begin</key>
			<string>=\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>tag-param-value-enclosed-3</key>
		<dict>
			<key>begin</key>
			<string>=\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>tag-param-value-unenclosed</key>
		<dict>
			<key>begin</key>
			<string>=(?=[^ \[\{\(])</string>
			<key>end</key>
			<string>\s|(?=[}\]\)]|:\s)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<key>tag-params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-param-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-param-value-unenclosed</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-param-value-enclosed-1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-param-value-enclosed-2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-param-value-enclosed-3</string>
				</dict>
			</array>
		</dict>
		<key>tag-unenclosed</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s*|:\s*)([A-Za-z.#][A-Za-z0-9_.#-]*+)(?![\[\{\(])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.tag.slim</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>text.slim.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby-content</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ruby-embedded</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-unenclosed</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.slim</string>
	<key>uuid</key>
	<string>35d59c9e-b2cf-4db3-95ac-807f5b067ecb</string>
</dict>
</plist>
